mitene_url: 'https://mitene.us/xxxx' # みてねURL（STRING）
mitene_password: 'xxxxxxxx' # みてねパスワード（STRING）
dl_dir_path: '/Users/OGAWA_Sanshiro/Desktop/DLフォルダ' # 画像・動画のDL先フォルダ 絶対パス（STRING）
dl_start_date: 2022-01-01 # DL対象撮影期間 始（yyyy-mm-dd）
dl_end_date: 2022-01-07 # DL対象撮影期間 終（yyyy-mm-dd）
dl_wait_time: 300 # DL時のタイムアウト設定 秒（INT）